# YAML for Mac DQN configuration

train:
  max_episode_length: 5000
  num_episodes: 1000
  batch_size: 32
  max_replay_len: 2000
  model_file: "dqn_model.h5"
  train_period: 5
  train_on_demonstrations: True
  demonstration_eval_episodes: 5
  demonstration_epochs: 2
  train_after_episode: False
  reinforce_good_episodes: 0
  good_ep_thresh: 15000

inference:
  only_inference: True
  num_inference_episodes: 10

demonstrations:
  state_file: "demonstrated_states.npz"
  obs_file: "demonstrated_observations.npz"
  act_file: "demonstrated_actions.npz"

gpu:
  device: -1 #-1 means use cpu

system: 
  os: "mac"
  arch: "x86_64"
  drone_sim: "drone_sim_external"
  demonstration_drone_sim: "drone_sim_player"

logging:
  console_lvl: "debug"
  log_prefix: "log/run_output"

#TODO add model specific params
